apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'http://charts.gitlab.io'
    chart: gitlab
    targetRevision: 7.8.1
    helm:
      valueFiles:
      - $values/argocd/helm/values/gitlab-values.yaml

  - repoURL: 'git@github.com:dareyio/terraform-aws-pipeline.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: production