apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: relax-sound
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.gabe565.com'
    chart: relax-sounds
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/argocd/helm/values/relax-sounds-values.yaml
  - repoURL: 'git@github.com:dareyio/terraform-aws-pipeline.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: production