name: Docker Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for deployment'
        required: true
        default: 'dev'
        # Add other environment options as desired

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Login to docker
      uses: docker/login-action@v3.0.0
      with: 
        username: dareyregistry
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}       
